package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Calle generated by hbm2java
 */
@Entity
@Table(name = "calle")
public class Calle implements java.io.Serializable {

	private int idcalle;
	private Ciudad ciudad;
	private String nombre;
	private Integer idzona;
	private Set<Interseccion> interseccionsForCallesec = new HashSet<Interseccion>(
			0);
	private Set<Interseccion> interseccionsForCalleprin = new HashSet<Interseccion>(
			0);

	public Calle() {
	}

	public Calle(int idcalle) {
		this.idcalle = idcalle;
	}

	public Calle(int idcalle, Ciudad ciudad, String nombre, Integer idzona,
			Set<Interseccion> interseccionsForCallesec,
			Set<Interseccion> interseccionsForCalleprin) {
		this.idcalle = idcalle;
		this.ciudad = ciudad;
		this.nombre = nombre;
		this.idzona = idzona;
		this.interseccionsForCallesec = interseccionsForCallesec;
		this.interseccionsForCalleprin = interseccionsForCalleprin;
	}

	@Id
	@Column(name = "idcalle", unique = true, nullable = false)
	public int getIdcalle() {
		return this.idcalle;
	}

	public void setIdcalle(int idcalle) {
		this.idcalle = idcalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigciu")
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "idzona")
	public Integer getIdzona() {
		return this.idzona;
	}

	public void setIdzona(Integer idzona) {
		this.idzona = idzona;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calleByCallesec")
	public Set<Interseccion> getInterseccionsForCallesec() {
		return this.interseccionsForCallesec;
	}

	public void setInterseccionsForCallesec(
			Set<Interseccion> interseccionsForCallesec) {
		this.interseccionsForCallesec = interseccionsForCallesec;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calleByCalleprin")
	public Set<Interseccion> getInterseccionsForCalleprin() {
		return this.interseccionsForCalleprin;
	}

	public void setInterseccionsForCalleprin(
			Set<Interseccion> interseccionsForCalleprin) {
		this.interseccionsForCalleprin = interseccionsForCalleprin;
	}

}
