package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad")
public class Ciudad implements java.io.Serializable {

	private int codigo;
	private Provincia provincia;
	private String nombre;
	private Set<Calle> calles = new HashSet<Calle>(0);

	public Ciudad() {
	}

	public Ciudad(int codigo) {
		this.codigo = codigo;
	}

	public Ciudad(int codigo, Provincia provincia, String nombre,
			Set<Calle> calles) {
		this.codigo = codigo;
		this.provincia = provincia;
		this.nombre = nombre;
		this.calles = calles;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprovincia")
	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<Calle> getCalles() {
		return this.calles;
	}

	public void setCalles(Set<Calle> calles) {
		this.calles = calles;
	}

}
