package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Colas generated by hbm2java
 */
@Entity
@Table(name = "colas")
public class Colas implements java.io.Serializable {

	private int id;
	private String nombre;
	private String telefono;
	private Long idmonitoreo;
	private String reloj;

	public Colas() {
	}

	public Colas(int id) {
		this.id = id;
	}

	public Colas(int id, String nombre, String telefono, Long idmonitoreo,
			String reloj) {
		this.id = id;
		this.nombre = nombre;
		this.telefono = telefono;
		this.idmonitoreo = idmonitoreo;
		this.reloj = reloj;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "idmonitoreo")
	public Long getIdmonitoreo() {
		return this.idmonitoreo;
	}

	public void setIdmonitoreo(Long idmonitoreo) {
		this.idmonitoreo = idmonitoreo;
	}

	@Column(name = "reloj")
	public String getReloj() {
		return this.reloj;
	}

	public void setReloj(String reloj) {
		this.reloj = reloj;
	}

}
