package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cooperativa generated by hbm2java
 */
@Entity
@Table(name = "cooperativa", uniqueConstraints = @UniqueConstraint(columnNames = "slug"))
public class Cooperativa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 621626496358589778L;
	private int idcooperativa;
	private String nombre;
	private String representanteLegal;
	private String ruc;
	private Long idempresa;
	private String slug;
	private String opciones;
	private Set<Unidad> unidads = new HashSet<Unidad>(0);
	private Set<Institucion> institucions = new HashSet<Institucion>(0);

	public Cooperativa() {
	}

	public Cooperativa(int idcooperativa, String slug) {
		this.idcooperativa = idcooperativa;
		this.slug = slug;
	}

	public Cooperativa(int idcooperativa, String nombre,
			String representanteLegal, String ruc, Long idempresa, String slug,
			String opciones, Set<Unidad> unidads, Set<Institucion> institucions) {
		this.idcooperativa = idcooperativa;
		this.nombre = nombre;
		this.representanteLegal = representanteLegal;
		this.ruc = ruc;
		this.idempresa = idempresa;
		this.slug = slug;
		this.opciones = opciones;
		this.unidads = unidads;
		this.institucions = institucions;
	}

	@Id
	@Column(name = "idcooperativa", unique = true, nullable = false)
	public int getIdcooperativa() {
		return this.idcooperativa;
	}

	public void setIdcooperativa(int idcooperativa) {
		this.idcooperativa = idcooperativa;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "representante_legal", length = 100)
	public String getRepresentanteLegal() {
		return this.representanteLegal;
	}

	public void setRepresentanteLegal(String representanteLegal) {
		this.representanteLegal = representanteLegal;
	}

	@Column(name = "ruc", length = 13)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "idempresa")
	public Long getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(Long idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "slug", unique = true, nullable = false, length = 128)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "opciones")
	public String getOpciones() {
		return this.opciones;
	}

	public void setOpciones(String opciones) {
		this.opciones = opciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cooperativa")
	public Set<Unidad> getUnidads() {
		return this.unidads;
	}

	public void setUnidads(Set<Unidad> unidads) {
		this.unidads = unidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cooperativa")
	public Set<Institucion> getInstitucions() {
		return this.institucions;
	}

	public void setInstitucions(Set<Institucion> institucions) {
		this.institucions = institucions;
	}

}
