package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion")
public class Direccion implements java.io.Serializable {

	private int iddireccion;
	private Interseccion interseccion;
	private FosUser fosUser;
	private String referencia;
	private String telefono;
	private String callenum;
	private String codigo;
	private Date created;
	private Date updated;
	private String sector;

	public Direccion() {
	}

	public Direccion(int iddireccion, Date created, Date updated) {
		this.iddireccion = iddireccion;
		this.created = created;
		this.updated = updated;
	}

	public Direccion(int iddireccion, Interseccion interseccion,
			FosUser fosUser, String referencia, String telefono,
			String callenum, String codigo, Date created, Date updated,
			String sector) {
		this.iddireccion = iddireccion;
		this.interseccion = interseccion;
		this.fosUser = fosUser;
		this.referencia = referencia;
		this.telefono = telefono;
		this.callenum = callenum;
		this.codigo = codigo;
		this.created = created;
		this.updated = updated;
		this.sector = sector;
	}

	@Id
	@Column(name = "iddireccion", unique = true, nullable = false)
	public int getIddireccion() {
		return this.iddireccion;
	}

	public void setIddireccion(int iddireccion) {
		this.iddireccion = iddireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interseccion")
	public Interseccion getInterseccion() {
		return this.interseccion;
	}

	public void setInterseccion(Interseccion interseccion) {
		this.interseccion = interseccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public FosUser getFosUser() {
		return this.fosUser;
	}

	public void setFosUser(FosUser fosUser) {
		this.fosUser = fosUser;
	}

	@Column(name = "referencia", length = 57)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "callenum", length = 10)
	public String getCallenum() {
		return this.callenum;
	}

	public void setCallenum(String callenum) {
		this.callenum = callenum;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 22)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 22)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "sector")
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

}
