package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dispositivo generated by hbm2java
 */
@Entity
@Table(name = "dispositivo")
public class Dispositivo implements java.io.Serializable {

	private int iddispositivo;
	private Tipocomunicacion tipocomunicacion;
	private Tipodispositivo tipodispositivo;
	private String codigo;
	private String numero;
	private String dirip;
	private String chip;
	private String imei;
	private boolean asignado;
	private boolean habilitado;
	private Set<Instalacion> instalacions = new HashSet<Instalacion>(0);
	private Set<Unidad> unidads = new HashSet<Unidad>(0);

	public Dispositivo() {
	}

	public Dispositivo(int iddispositivo, boolean asignado, boolean habilitado) {
		this.iddispositivo = iddispositivo;
		this.asignado = asignado;
		this.habilitado = habilitado;
	}

	public Dispositivo(int iddispositivo, Tipocomunicacion tipocomunicacion,
			Tipodispositivo tipodispositivo, String codigo, String numero,
			String dirip, String chip, String imei, boolean asignado,
			boolean habilitado, Set<Instalacion> instalacions,
			Set<Unidad> unidads) {
		this.iddispositivo = iddispositivo;
		this.tipocomunicacion = tipocomunicacion;
		this.tipodispositivo = tipodispositivo;
		this.codigo = codigo;
		this.numero = numero;
		this.dirip = dirip;
		this.chip = chip;
		this.imei = imei;
		this.asignado = asignado;
		this.habilitado = habilitado;
		this.instalacions = instalacions;
		this.unidads = unidads;
	}

	@Id
	@Column(name = "iddispositivo", unique = true, nullable = false)
	public int getIddispositivo() {
		return this.iddispositivo;
	}

	public void setIddispositivo(int iddispositivo) {
		this.iddispositivo = iddispositivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipocomunicacion")
	public Tipocomunicacion getTipocomunicacion() {
		return this.tipocomunicacion;
	}

	public void setTipocomunicacion(Tipocomunicacion tipocomunicacion) {
		this.tipocomunicacion = tipocomunicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipodispositivo")
	public Tipodispositivo getTipodispositivo() {
		return this.tipodispositivo;
	}

	public void setTipodispositivo(Tipodispositivo tipodispositivo) {
		this.tipodispositivo = tipodispositivo;
	}

	@Column(name = "codigo", length = 100)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "numero", length = 100)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "dirip", length = 100)
	public String getDirip() {
		return this.dirip;
	}

	public void setDirip(String dirip) {
		this.dirip = dirip;
	}

	@Column(name = "chip", length = 100)
	public String getChip() {
		return this.chip;
	}

	public void setChip(String chip) {
		this.chip = chip;
	}

	@Column(name = "imei", length = 100)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Column(name = "asignado", nullable = false)
	public boolean isAsignado() {
		return this.asignado;
	}

	public void setAsignado(boolean asignado) {
		this.asignado = asignado;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dispositivo")
	public Set<Instalacion> getInstalacions() {
		return this.instalacions;
	}

	public void setInstalacions(Set<Instalacion> instalacions) {
		this.instalacions = instalacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dispositivo")
	public Set<Unidad> getUnidads() {
		return this.unidads;
	}

	public void setUnidads(Set<Unidad> unidads) {
		this.unidads = unidads;
	}

}
