package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email")
public class Email implements java.io.Serializable {

	private int id;
	private FosUser fosUser;
	private String email;

	public Email() {
	}

	public Email(int id, String email) {
		this.id = id;
		this.email = email;
	}

	public Email(int id, FosUser fosUser, String email) {
		this.id = id;
		this.fosUser = fosUser;
		this.email = email;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public FosUser getFosUser() {
		return this.fosUser;
	}

	public void setFosUser(FosUser fosUser) {
		this.fosUser = fosUser;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
