package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Enviocomando generated by hbm2java
 */
@Entity
@Table(name = "enviocomando")
public class Enviocomando implements java.io.Serializable {

	private int idmensaje;
	private Comando comando;
	private Tipocomunicacion tipocomunicacion;
	private Tipodispositivo tipodispositivo;
	private Integer orden;
	private String funcion;

	public Enviocomando() {
	}

	public Enviocomando(int idmensaje) {
		this.idmensaje = idmensaje;
	}

	public Enviocomando(int idmensaje, Comando comando,
			Tipocomunicacion tipocomunicacion, Tipodispositivo tipodispositivo,
			Integer orden, String funcion) {
		this.idmensaje = idmensaje;
		this.comando = comando;
		this.tipocomunicacion = tipocomunicacion;
		this.tipodispositivo = tipodispositivo;
		this.orden = orden;
		this.funcion = funcion;
	}

	@Id
	@Column(name = "idmensaje", unique = true, nullable = false)
	public int getIdmensaje() {
		return this.idmensaje;
	}

	public void setIdmensaje(int idmensaje) {
		this.idmensaje = idmensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comando")
	public Comando getComando() {
		return this.comando;
	}

	public void setComando(Comando comando) {
		this.comando = comando;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipocomunicacion")
	public Tipocomunicacion getTipocomunicacion() {
		return this.tipocomunicacion;
	}

	public void setTipocomunicacion(Tipocomunicacion tipocomunicacion) {
		this.tipocomunicacion = tipocomunicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipodispositivo")
	public Tipodispositivo getTipodispositivo() {
		return this.tipodispositivo;
	}

	public void setTipodispositivo(Tipodispositivo tipodispositivo) {
		this.tipodispositivo = tipodispositivo;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "funcion")
	public String getFuncion() {
		return this.funcion;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

}
