package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * ExtLogEntries generated by hbm2java
 */
@Entity
@Table(name = "ext_log_entries")
public class ExtLogEntries implements java.io.Serializable {

	private int id;
	private int version;
	private String action;
	private Date loggedAt;
	private String objectId;
	private String objectClass;
	private String data;
	private String username;

	public ExtLogEntries() {
	}

	public ExtLogEntries(int id, String action, Date loggedAt,
			String objectClass) {
		this.id = id;
		this.action = action;
		this.loggedAt = loggedAt;
		this.objectClass = objectClass;
	}

	public ExtLogEntries(int id, String action, Date loggedAt, String objectId,
			String objectClass, String data, String username) {
		this.id = id;
		this.action = action;
		this.loggedAt = loggedAt;
		this.objectId = objectId;
		this.objectClass = objectClass;
		this.data = data;
		this.username = username;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "action", nullable = false, length = 8)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logged_at", nullable = false, length = 22)
	public Date getLoggedAt() {
		return this.loggedAt;
	}

	public void setLoggedAt(Date loggedAt) {
		this.loggedAt = loggedAt;
	}

	@Column(name = "object_id", length = 32)
	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	@Column(name = "object_class", nullable = false)
	public String getObjectClass() {
		return this.objectClass;
	}

	public void setObjectClass(String objectClass) {
		this.objectClass = objectClass;
	}

	@Column(name = "data")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
