package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FosGroup generated by hbm2java
 */
@Entity
@Table(name = "fos_group", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class FosGroup implements java.io.Serializable {

	private int id;
	private String name;
	private String roles;
	private Set<FosUser> fosUsers = new HashSet<FosUser>(0);

	public FosGroup() {
	}

	public FosGroup(int id, String name, String roles) {
		this.id = id;
		this.name = name;
		this.roles = roles;
	}

	public FosGroup(int id, String name, String roles, Set<FosUser> fosUsers) {
		this.id = id;
		this.name = name;
		this.roles = roles;
		this.fosUsers = fosUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "roles", nullable = false)
	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "fos_user_group", joinColumns = { @JoinColumn(name = "group_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<FosUser> getFosUsers() {
		return this.fosUsers;
	}

	public void setFosUsers(Set<FosUser> fosUsers) {
		this.fosUsers = fosUsers;
	}

}
