package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Institucion generated by hbm2java
 */
@Entity
@Table(name = "institucion", uniqueConstraints = @UniqueConstraint(columnNames = "slug"))
public class Institucion implements java.io.Serializable {

	private int id;
	private Cooperativa cooperativa;
	private String nombre;
	private String slug;
	private String opciones;
	private Set<Unidad> unidads = new HashSet<Unidad>(0);

	public Institucion() {
	}

	public Institucion(int id, String slug) {
		this.id = id;
		this.slug = slug;
	}

	public Institucion(int id, Cooperativa cooperativa, String nombre,
			String slug, String opciones, Set<Unidad> unidads) {
		this.id = id;
		this.cooperativa = cooperativa;
		this.nombre = nombre;
		this.slug = slug;
		this.opciones = opciones;
		this.unidads = unidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cooperativa")
	public Cooperativa getCooperativa() {
		return this.cooperativa;
	}

	public void setCooperativa(Cooperativa cooperativa) {
		this.cooperativa = cooperativa;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "slug", unique = true, nullable = false, length = 128)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "opciones")
	public String getOpciones() {
		return this.opciones;
	}

	public void setOpciones(String opciones) {
		this.opciones = opciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institucion")
	public Set<Unidad> getUnidads() {
		return this.unidads;
	}

	public void setUnidads(Set<Unidad> unidads) {
		this.unidads = unidads;
	}

}
