package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Instalacion generated by hbm2java
 */
@Entity
@Table(name = "instalacion")
public class Instalacion implements java.io.Serializable {

	private int idinstalacion;
	private FosUser fosUser;
	private Unidad unidad;
	private Dispositivo dispositivo;
	private Date fechahora;
	private Date created;
	private Date updated;

	public Instalacion() {
	}

	public Instalacion(int idinstalacion, Date created, Date updated) {
		this.idinstalacion = idinstalacion;
		this.created = created;
		this.updated = updated;
	}

	public Instalacion(int idinstalacion, FosUser fosUser, Unidad unidad,
			Dispositivo dispositivo, Date fechahora, Date created, Date updated) {
		this.idinstalacion = idinstalacion;
		this.fosUser = fosUser;
		this.unidad = unidad;
		this.dispositivo = dispositivo;
		this.fechahora = fechahora;
		this.created = created;
		this.updated = updated;
	}

	@Id
	@Column(name = "idinstalacion", unique = true, nullable = false)
	public int getIdinstalacion() {
		return this.idinstalacion;
	}

	public void setIdinstalacion(int idinstalacion) {
		this.idinstalacion = idinstalacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instalador")
	public FosUser getFosUser() {
		return this.fosUser;
	}

	public void setFosUser(FosUser fosUser) {
		this.fosUser = fosUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idunidad")
	public Unidad getUnidad() {
		return this.unidad;
	}

	public void setUnidad(Unidad unidad) {
		this.unidad = unidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dispositivo")
	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechahora", length = 22)
	public Date getFechahora() {
		return this.fechahora;
	}

	public void setFechahora(Date fechahora) {
		this.fechahora = fechahora;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 22)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 22)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
