package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MediaGalleryMedia generated by hbm2java
 */
@Entity
@Table(name = "media__gallery_media")
public class MediaGalleryMedia implements java.io.Serializable {

	private int id;
	private MediaGallery mediaGallery;
	private MediaMedia mediaMedia;
	private int position;
	private boolean enabled;
	private Date updatedAt;
	private Date createdAt;

	public MediaGalleryMedia() {
	}

	public MediaGalleryMedia(int id, int position, boolean enabled,
			Date updatedAt, Date createdAt) {
		this.id = id;
		this.position = position;
		this.enabled = enabled;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
	}

	public MediaGalleryMedia(int id, MediaGallery mediaGallery,
			MediaMedia mediaMedia, int position, boolean enabled,
			Date updatedAt, Date createdAt) {
		this.id = id;
		this.mediaGallery = mediaGallery;
		this.mediaMedia = mediaMedia;
		this.position = position;
		this.enabled = enabled;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gallery_id")
	public MediaGallery getMediaGallery() {
		return this.mediaGallery;
	}

	public void setMediaGallery(MediaGallery mediaGallery) {
		this.mediaGallery = mediaGallery;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "media_id")
	public MediaMedia getMediaMedia() {
		return this.mediaMedia;
	}

	public void setMediaMedia(MediaMedia mediaMedia) {
		this.mediaMedia = mediaMedia;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 22)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 22)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
