package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MediaGallery generated by hbm2java
 */
@Entity
@Table(name = "media__gallery")
public class MediaGallery implements java.io.Serializable {

	private int id;
	private String name;
	private String context;
	private String defaultFormat;
	private boolean enabled;
	private Date updatedAt;
	private Date createdAt;
	private Set<MediaGalleryMedia> mediaGalleryMedias = new HashSet<MediaGalleryMedia>(
			0);

	public MediaGallery() {
	}

	public MediaGallery(int id, String name, String context,
			String defaultFormat, boolean enabled, Date updatedAt,
			Date createdAt) {
		this.id = id;
		this.name = name;
		this.context = context;
		this.defaultFormat = defaultFormat;
		this.enabled = enabled;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
	}

	public MediaGallery(int id, String name, String context,
			String defaultFormat, boolean enabled, Date updatedAt,
			Date createdAt, Set<MediaGalleryMedia> mediaGalleryMedias) {
		this.id = id;
		this.name = name;
		this.context = context;
		this.defaultFormat = defaultFormat;
		this.enabled = enabled;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
		this.mediaGalleryMedias = mediaGalleryMedias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "context", nullable = false)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "default_format", nullable = false)
	public String getDefaultFormat() {
		return this.defaultFormat;
	}

	public void setDefaultFormat(String defaultFormat) {
		this.defaultFormat = defaultFormat;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 22)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 22)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mediaGallery")
	public Set<MediaGalleryMedia> getMediaGalleryMedias() {
		return this.mediaGalleryMedias;
	}

	public void setMediaGalleryMedias(Set<MediaGalleryMedia> mediaGalleryMedias) {
		this.mediaGalleryMedias = mediaGalleryMedias;
	}

}
