package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MediaMedia generated by hbm2java
 */
@Entity
@Table(name = "media__media")
public class MediaMedia implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private boolean enabled;
	private String providerName;
	private int providerStatus;
	private String providerReference;
	private String providerMetadata;
	private Integer width;
	private Integer height;
	private Long length;
	private String contentType;
	private Integer contentSize;
	private String copyright;
	private String authorName;
	private String context;
	private Boolean cdnIsFlushable;
	private Date cdnFlushAt;
	private Date updatedAt;
	private Date createdAt;
	private Set<MediaGalleryMedia> mediaGalleryMedias = new HashSet<MediaGalleryMedia>(
			0);

	public MediaMedia() {
	}

	public MediaMedia(int id, String name, boolean enabled,
			String providerName, int providerStatus, String providerReference,
			Date updatedAt, Date createdAt) {
		this.id = id;
		this.name = name;
		this.enabled = enabled;
		this.providerName = providerName;
		this.providerStatus = providerStatus;
		this.providerReference = providerReference;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
	}

	public MediaMedia(int id, String name, String description, boolean enabled,
			String providerName, int providerStatus, String providerReference,
			String providerMetadata, Integer width, Integer height,
			Long length, String contentType, Integer contentSize,
			String copyright, String authorName, String context,
			Boolean cdnIsFlushable, Date cdnFlushAt, Date updatedAt,
			Date createdAt, Set<MediaGalleryMedia> mediaGalleryMedias) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.enabled = enabled;
		this.providerName = providerName;
		this.providerStatus = providerStatus;
		this.providerReference = providerReference;
		this.providerMetadata = providerMetadata;
		this.width = width;
		this.height = height;
		this.length = length;
		this.contentType = contentType;
		this.contentSize = contentSize;
		this.copyright = copyright;
		this.authorName = authorName;
		this.context = context;
		this.cdnIsFlushable = cdnIsFlushable;
		this.cdnFlushAt = cdnFlushAt;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
		this.mediaGalleryMedias = mediaGalleryMedias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "provider_name", nullable = false)
	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	@Column(name = "provider_status", nullable = false)
	public int getProviderStatus() {
		return this.providerStatus;
	}

	public void setProviderStatus(int providerStatus) {
		this.providerStatus = providerStatus;
	}

	@Column(name = "provider_reference", nullable = false)
	public String getProviderReference() {
		return this.providerReference;
	}

	public void setProviderReference(String providerReference) {
		this.providerReference = providerReference;
	}

	@Column(name = "provider_metadata")
	public String getProviderMetadata() {
		return this.providerMetadata;
	}

	public void setProviderMetadata(String providerMetadata) {
		this.providerMetadata = providerMetadata;
	}

	@Column(name = "width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "length", precision = 10, scale = 0)
	public Long getLength() {
		return this.length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

	@Column(name = "content_type", length = 64)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "content_size")
	public Integer getContentSize() {
		return this.contentSize;
	}

	public void setContentSize(Integer contentSize) {
		this.contentSize = contentSize;
	}

	@Column(name = "copyright")
	public String getCopyright() {
		return this.copyright;
	}

	public void setCopyright(String copyright) {
		this.copyright = copyright;
	}

	@Column(name = "author_name")
	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	@Column(name = "context", length = 16)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "cdn_is_flushable")
	public Boolean getCdnIsFlushable() {
		return this.cdnIsFlushable;
	}

	public void setCdnIsFlushable(Boolean cdnIsFlushable) {
		this.cdnIsFlushable = cdnIsFlushable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cdn_flush_at", length = 22)
	public Date getCdnFlushAt() {
		return this.cdnFlushAt;
	}

	public void setCdnFlushAt(Date cdnFlushAt) {
		this.cdnFlushAt = cdnFlushAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 22)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 22)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mediaMedia")
	public Set<MediaGalleryMedia> getMediaGalleryMedias() {
		return this.mediaGalleryMedias;
	}

	public void setMediaGalleryMedias(Set<MediaGalleryMedia> mediaGalleryMedias) {
		this.mediaGalleryMedias = mediaGalleryMedias;
	}

}
