package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensajes generated by hbm2java
 */
@Entity
@Table(name = "mensajes")
public class Mensajes implements java.io.Serializable {

	private int idmensaje;
	private Unidad unidad;
	private FosUser fosUser;
	private String destino;
	private Double puerto;
	private String texto;
	private Boolean enviado;
	private Date fechahora;
	private String tipoenvio;
	private String recibe;
	private Date recibido;
	private String mensaje;

	public Mensajes() {
	}

	public Mensajes(int idmensaje) {
		this.idmensaje = idmensaje;
	}

	public Mensajes(int idmensaje, Unidad unidad, FosUser fosUser,
			String destino, Double puerto, String texto, Boolean enviado,
			Date fechahora, String tipoenvio, String recibe, Date recibido,
			String mensaje) {
		this.idmensaje = idmensaje;
		this.unidad = unidad;
		this.fosUser = fosUser;
		this.destino = destino;
		this.puerto = puerto;
		this.texto = texto;
		this.enviado = enviado;
		this.fechahora = fechahora;
		this.tipoenvio = tipoenvio;
		this.recibe = recibe;
		this.recibido = recibido;
		this.mensaje = mensaje;
	}

	@Id
	@Column(name = "idmensaje", unique = true, nullable = false)
	public int getIdmensaje() {
		return this.idmensaje;
	}

	public void setIdmensaje(int idmensaje) {
		this.idmensaje = idmensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidad")
	public Unidad getUnidad() {
		return this.unidad;
	}

	public void setUnidad(Unidad unidad) {
		this.unidad = unidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public FosUser getFosUser() {
		return this.fosUser;
	}

	public void setFosUser(FosUser fosUser) {
		this.fosUser = fosUser;
	}

	@Column(name = "destino")
	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	@Column(name = "puerto", precision = 17, scale = 17)
	public Double getPuerto() {
		return this.puerto;
	}

	public void setPuerto(Double puerto) {
		this.puerto = puerto;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "enviado")
	public Boolean getEnviado() {
		return this.enviado;
	}

	public void setEnviado(Boolean enviado) {
		this.enviado = enviado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechahora", length = 22)
	public Date getFechahora() {
		return this.fechahora;
	}

	public void setFechahora(Date fechahora) {
		this.fechahora = fechahora;
	}

	@Column(name = "tipoenvio")
	public String getTipoenvio() {
		return this.tipoenvio;
	}

	public void setTipoenvio(String tipoenvio) {
		this.tipoenvio = tipoenvio;
	}

	@Column(name = "recibe")
	public String getRecibe() {
		return this.recibe;
	}

	public void setRecibe(String recibe) {
		this.recibe = recibe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recibido", length = 22)
	public Date getRecibido() {
		return this.recibido;
	}

	public void setRecibido(Date recibido) {
		this.recibido = recibido;
	}

	@Column(name = "mensaje")
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

}
