package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operadora generated by hbm2java
 */
@Entity
@Table(name = "operadora")
public class Operadora implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<Celular> celulars = new HashSet<Celular>(0);

	public Operadora() {
	}

	public Operadora(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Operadora(int id, String nombre, Set<Celular> celulars) {
		this.id = id;
		this.nombre = nombre;
		this.celulars = celulars;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadora")
	public Set<Celular> getCelulars() {
		return this.celulars;
	}

	public void setCelulars(Set<Celular> celulars) {
		this.celulars = celulars;
	}

}
