package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Propietario generated by hbm2java
 */
@Entity
@Table(name = "propietario", uniqueConstraints = @UniqueConstraint(columnNames = "user_id"))
public class Propietario implements java.io.Serializable {

	private int id;
	private FosUser fosUser;

	public Propietario() {
	}

	public Propietario(int id) {
		this.id = id;
	}

	public Propietario(int id, FosUser fosUser) {
		this.id = id;
		this.fosUser = fosUser;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", unique = true)
	public FosUser getFosUser() {
		return this.fosUser;
	}

	public void setFosUser(FosUser fosUser) {
		this.fosUser = fosUser;
	}

}
