package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recorrido generated by hbm2java
 */
@Entity
@Table(name = "recorrido")
public class Recorrido implements java.io.Serializable {

	private int idrecorrido;
	private Despacho despacho;
	private Monitoreo monitoreo;

	public Recorrido() {
	}

	public Recorrido(int idrecorrido) {
		this.idrecorrido = idrecorrido;
	}

	public Recorrido(int idrecorrido, Despacho despacho, Monitoreo monitoreo) {
		this.idrecorrido = idrecorrido;
		this.despacho = despacho;
		this.monitoreo = monitoreo;
	}

	@Id
	@Column(name = "idrecorrido", unique = true, nullable = false)
	public int getIdrecorrido() {
		return this.idrecorrido;
	}

	public void setIdrecorrido(int idrecorrido) {
		this.idrecorrido = idrecorrido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "despacho")
	public Despacho getDespacho() {
		return this.despacho;
	}

	public void setDespacho(Despacho despacho) {
		this.despacho = despacho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "monitoreo")
	public Monitoreo getMonitoreo() {
		return this.monitoreo;
	}

	public void setMonitoreo(Monitoreo monitoreo) {
		this.monitoreo = monitoreo;
	}

}
