package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "telefono")
public class Telefono implements java.io.Serializable {

	private int id;
	private FosUser fosUser;
	private String numero;
	private Integer orden;

	public Telefono() {
	}

	public Telefono(int id, String numero) {
		this.id = id;
		this.numero = numero;
	}

	public Telefono(int id, FosUser fosUser, String numero, Integer orden) {
		this.id = id;
		this.fosUser = fosUser;
		this.numero = numero;
		this.orden = orden;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public FosUser getFosUser() {
		return this.fosUser;
	}

	public void setFosUser(FosUser fosUser) {
		this.fosUser = fosUser;
	}

	@Column(name = "numero", nullable = false)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

}
