package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipotrama generated by hbm2java
 */
@Entity
@Table(name = "tipotrama")
public class Tipotrama implements java.io.Serializable {

	private String codigo;
	private String descripcion;
	private Boolean alerta;
	private String color;
	private Set<Monitoreo> monitoreos = new HashSet<Monitoreo>(0);

	public Tipotrama() {
	}

	public Tipotrama(String codigo) {
		this.codigo = codigo;
	}

	public Tipotrama(String codigo, String descripcion, Boolean alerta,
			String color, Set<Monitoreo> monitoreos) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.alerta = alerta;
		this.color = color;
		this.monitoreos = monitoreos;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "alerta")
	public Boolean getAlerta() {
		return this.alerta;
	}

	public void setAlerta(Boolean alerta) {
		this.alerta = alerta;
	}

	@Column(name = "color")
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipotrama")
	public Set<Monitoreo> getMonitoreos() {
		return this.monitoreos;
	}

	public void setMonitoreos(Set<Monitoreo> monitoreos) {
		this.monitoreos = monitoreos;
	}

}
