package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipodispositivo generated by hbm2java
 */
@Entity
@Table(name = "tipodispositivo")
public class Tipodispositivo implements java.io.Serializable {

	private int idtipodispositivo;
	private String nombre;
	private String campos;
	private Set<Enviocomando> enviocomandos = new HashSet<Enviocomando>(0);
	private Set<Dispositivo> dispositivos = new HashSet<Dispositivo>(0);

	public Tipodispositivo() {
	}

	public Tipodispositivo(int idtipodispositivo) {
		this.idtipodispositivo = idtipodispositivo;
	}

	public Tipodispositivo(int idtipodispositivo, String nombre, String campos,
			Set<Enviocomando> enviocomandos, Set<Dispositivo> dispositivos) {
		this.idtipodispositivo = idtipodispositivo;
		this.nombre = nombre;
		this.campos = campos;
		this.enviocomandos = enviocomandos;
		this.dispositivos = dispositivos;
	}

	@Id
	@Column(name = "idtipodispositivo", unique = true, nullable = false)
	public int getIdtipodispositivo() {
		return this.idtipodispositivo;
	}

	public void setIdtipodispositivo(int idtipodispositivo) {
		this.idtipodispositivo = idtipodispositivo;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "campos")
	public String getCampos() {
		return this.campos;
	}

	public void setCampos(String campos) {
		this.campos = campos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipodispositivo")
	public Set<Enviocomando> getEnviocomandos() {
		return this.enviocomandos;
	}

	public void setEnviocomandos(Set<Enviocomando> enviocomandos) {
		this.enviocomandos = enviocomandos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipodispositivo")
	public Set<Dispositivo> getDispositivos() {
		return this.dispositivos;
	}

	public void setDispositivos(Set<Dispositivo> dispositivos) {
		this.dispositivos = dispositivos;
	}

}
