package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name = "tipo")
public class Tipo implements java.io.Serializable {

	private int idtipo;
	private String nombre;
	private String opciones;
	private Set<Unidad> unidads = new HashSet<Unidad>(0);

	public Tipo() {
	}

	public Tipo(int idtipo) {
		this.idtipo = idtipo;
	}

	public Tipo(int idtipo, String nombre, String opciones, Set<Unidad> unidads) {
		this.idtipo = idtipo;
		this.nombre = nombre;
		this.opciones = opciones;
		this.unidads = unidads;
	}

	@Id
	@Column(name = "idtipo", unique = true, nullable = false)
	public int getIdtipo() {
		return this.idtipo;
	}

	public void setIdtipo(int idtipo) {
		this.idtipo = idtipo;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "opciones")
	public String getOpciones() {
		return this.opciones;
	}

	public void setOpciones(String opciones) {
		this.opciones = opciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipo")
	public Set<Unidad> getUnidads() {
		return this.unidads;
	}

	public void setUnidads(Set<Unidad> unidads) {
		this.unidads = unidads;
	}

}
