package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocomunicacion generated by hbm2java
 */
@Entity
@Table(name = "tipocomunicacion")
public class Tipocomunicacion implements java.io.Serializable {

	private int idtipocomunicacion;
	private String nombre;
	private Set<Dispositivo> dispositivos = new HashSet<Dispositivo>(0);
	private Set<Enviocomando> enviocomandos = new HashSet<Enviocomando>(0);

	public Tipocomunicacion() {
	}

	public Tipocomunicacion(int idtipocomunicacion) {
		this.idtipocomunicacion = idtipocomunicacion;
	}

	public Tipocomunicacion(int idtipocomunicacion, String nombre,
			Set<Dispositivo> dispositivos, Set<Enviocomando> enviocomandos) {
		this.idtipocomunicacion = idtipocomunicacion;
		this.nombre = nombre;
		this.dispositivos = dispositivos;
		this.enviocomandos = enviocomandos;
	}

	@Id
	@Column(name = "idtipocomunicacion", unique = true, nullable = false)
	public int getIdtipocomunicacion() {
		return this.idtipocomunicacion;
	}

	public void setIdtipocomunicacion(int idtipocomunicacion) {
		this.idtipocomunicacion = idtipocomunicacion;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocomunicacion")
	public Set<Dispositivo> getDispositivos() {
		return this.dispositivos;
	}

	public void setDispositivos(Set<Dispositivo> dispositivos) {
		this.dispositivos = dispositivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocomunicacion")
	public Set<Enviocomando> getEnviocomandos() {
		return this.enviocomandos;
	}

	public void setEnviocomandos(Set<Enviocomando> enviocomandos) {
		this.enviocomandos = enviocomandos;
	}

}
