package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ultimoregistro generated by hbm2java
 */
@Entity
@Table(name = "ultimoregistro", uniqueConstraints = @UniqueConstraint(columnNames = "monitoreo_id"))
public class Ultimoregistro implements java.io.Serializable {

	private int id;
	private Monitoreo monitoreo;

	public Ultimoregistro() {
	}

	public Ultimoregistro(int id) {
		this.id = id;
	}

	public Ultimoregistro(int id, Monitoreo monitoreo) {
		this.id = id;
		this.monitoreo = monitoreo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "monitoreo_id", unique = true)
	public Monitoreo getMonitoreo() {
		return this.monitoreo;
	}

	public void setMonitoreo(Monitoreo monitoreo) {
		this.monitoreo = monitoreo;
	}

}
