package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Unidad generated by hbm2java
 */
@Entity
@Table(name = "unidad", uniqueConstraints = {
		@UniqueConstraint(columnNames = "dispositivo"),
		@UniqueConstraint(columnNames = "slug") })
public class Unidad implements java.io.Serializable {

	private int idunidad;
	private Marca marca;
	private Institucion institucion;
	private Tipo tipo;
	private Dispositivo dispositivo;
	private Cooperativa cooperativa;
	private FosUser fosUser;
	private Integer codigo;
	private String alias;
	private String codigomunicipal;
	private String clase;
	private Long aniofab;
	private String idpaisorigen;
	private String nummotor;
	private String numchasis;
	private String color;
	private Boolean habilitado;
	private Long idpropietario;
	private String slug;
	private String salt;
	private String hash;
	private Date created;
	private Date updated;
	private String path;
	private String pathvideo;
	private String placa;
	private String modelo;
	private String numdis;
	private Set<Mensajes> mensajeses = new HashSet<Mensajes>(0);
	private Set<Despacho> despachos = new HashSet<Despacho>(0);
	private Set<Instalacion> instalacions = new HashSet<Instalacion>(0);
	private Set<Monitoreo> monitoreos = new HashSet<Monitoreo>(0);

	public Unidad() {
	}

	public Unidad(int idunidad, String slug, Date created, Date updated) {
		this.idunidad = idunidad;
		this.slug = slug;
		this.created = created;
		this.updated = updated;
	}

	public Unidad(int idunidad, Marca marca, Institucion institucion,
			Tipo tipo, Dispositivo dispositivo, Cooperativa cooperativa,
			FosUser fosUser, Integer codigo, String alias,
			String codigomunicipal, String clase, Long aniofab,
			String idpaisorigen, String nummotor, String numchasis,
			String color, Boolean habilitado, Long idpropietario, String slug,
			String salt, String hash, Date created, Date updated, String path,
			String pathvideo, String placa, String modelo, String numdis,
			Set<Mensajes> mensajeses, Set<Despacho> despachos,
			Set<Instalacion> instalacions, Set<Monitoreo> monitoreos) {
		this.idunidad = idunidad;
		this.marca = marca;
		this.institucion = institucion;
		this.tipo = tipo;
		this.dispositivo = dispositivo;
		this.cooperativa = cooperativa;
		this.fosUser = fosUser;
		this.codigo = codigo;
		this.alias = alias;
		this.codigomunicipal = codigomunicipal;
		this.clase = clase;
		this.aniofab = aniofab;
		this.idpaisorigen = idpaisorigen;
		this.nummotor = nummotor;
		this.numchasis = numchasis;
		this.color = color;
		this.habilitado = habilitado;
		this.idpropietario = idpropietario;
		this.slug = slug;
		this.salt = salt;
		this.hash = hash;
		this.created = created;
		this.updated = updated;
		this.path = path;
		this.pathvideo = pathvideo;
		this.placa = placa;
		this.modelo = modelo;
		this.numdis = numdis;
		this.mensajeses = mensajeses;
		this.despachos = despachos;
		this.instalacions = instalacions;
		this.monitoreos = monitoreos;
	}

	@Id
	@Column(name = "idunidad", unique = true, nullable = false)
	public int getIdunidad() {
		return this.idunidad;
	}

	public void setIdunidad(int idunidad) {
		this.idunidad = idunidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "marca")
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "institucion")
	public Institucion getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(Institucion institucion) {
		this.institucion = institucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo")
	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dispositivo", unique = true)
	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcooperativa")
	public Cooperativa getCooperativa() {
		return this.cooperativa;
	}

	public void setCooperativa(Cooperativa cooperativa) {
		this.cooperativa = cooperativa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "propietario")
	public FosUser getFosUser() {
		return this.fosUser;
	}

	public void setFosUser(FosUser fosUser) {
		this.fosUser = fosUser;
	}

	@Column(name = "codigo")
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "alias")
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "codigomunicipal")
	public String getCodigomunicipal() {
		return this.codigomunicipal;
	}

	public void setCodigomunicipal(String codigomunicipal) {
		this.codigomunicipal = codigomunicipal;
	}

	@Column(name = "clase")
	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	@Column(name = "aniofab")
	public Long getAniofab() {
		return this.aniofab;
	}

	public void setAniofab(Long aniofab) {
		this.aniofab = aniofab;
	}

	@Column(name = "idpaisorigen")
	public String getIdpaisorigen() {
		return this.idpaisorigen;
	}

	public void setIdpaisorigen(String idpaisorigen) {
		this.idpaisorigen = idpaisorigen;
	}

	@Column(name = "nummotor")
	public String getNummotor() {
		return this.nummotor;
	}

	public void setNummotor(String nummotor) {
		this.nummotor = nummotor;
	}

	@Column(name = "numchasis")
	public String getNumchasis() {
		return this.numchasis;
	}

	public void setNumchasis(String numchasis) {
		this.numchasis = numchasis;
	}

	@Column(name = "color")
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "habilitado")
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@Column(name = "idpropietario")
	public Long getIdpropietario() {
		return this.idpropietario;
	}

	public void setIdpropietario(Long idpropietario) {
		this.idpropietario = idpropietario;
	}

	@Column(name = "slug", unique = true, nullable = false, length = 128)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "salt")
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "hash")
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 22)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 22)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "pathvideo")
	public String getPathvideo() {
		return this.pathvideo;
	}

	public void setPathvideo(String pathvideo) {
		this.pathvideo = pathvideo;
	}

	@Column(name = "placa")
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "modelo")
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "numdis")
	public String getNumdis() {
		return this.numdis;
	}

	public void setNumdis(String numdis) {
		this.numdis = numdis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidad")
	public Set<Mensajes> getMensajeses() {
		return this.mensajeses;
	}

	public void setMensajeses(Set<Mensajes> mensajeses) {
		this.mensajeses = mensajeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidad")
	public Set<Despacho> getDespachos() {
		return this.despachos;
	}

	public void setDespachos(Set<Despacho> despachos) {
		this.despachos = despachos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidad")
	public Set<Instalacion> getInstalacions() {
		return this.instalacions;
	}

	public void setInstalacions(Set<Instalacion> instalacions) {
		this.instalacions = instalacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidad")
	public Set<Monitoreo> getMonitoreos() {
		return this.monitoreos;
	}

	public void setMonitoreos(Set<Monitoreo> monitoreos) {
		this.monitoreos = monitoreos;
	}

}
