package com.generado;

// Generated 11-dic-2012 20:33:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuariotraspaso generated by hbm2java
 */
@Entity
@Table(name = "usuariotraspaso")
public class Usuariotraspaso implements java.io.Serializable {

	private int id;
	private String codigo;
	private String nombre;
	private String nombreFin;
	private String apellido;
	private String telefono;
	private String prin;
	private String sec;
	private String adicional;
	private String masinf;
	private String sector;

	public Usuariotraspaso() {
	}

	public Usuariotraspaso(int id) {
		this.id = id;
	}

	public Usuariotraspaso(int id, String codigo, String nombre,
			String nombreFin, String apellido, String telefono, String prin,
			String sec, String adicional, String masinf, String sector) {
		this.id = id;
		this.codigo = codigo;
		this.nombre = nombre;
		this.nombreFin = nombreFin;
		this.apellido = apellido;
		this.telefono = telefono;
		this.prin = prin;
		this.sec = sec;
		this.adicional = adicional;
		this.masinf = masinf;
		this.sector = sector;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "nombre_fin")
	public String getNombreFin() {
		return this.nombreFin;
	}

	public void setNombreFin(String nombreFin) {
		this.nombreFin = nombreFin;
	}

	@Column(name = "apellido")
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "prin")
	public String getPrin() {
		return this.prin;
	}

	public void setPrin(String prin) {
		this.prin = prin;
	}

	@Column(name = "sec")
	public String getSec() {
		return this.sec;
	}

	public void setSec(String sec) {
		this.sec = sec;
	}

	@Column(name = "adicional")
	public String getAdicional() {
		return this.adicional;
	}

	public void setAdicional(String adicional) {
		this.adicional = adicional;
	}

	@Column(name = "masinf")
	public String getMasinf() {
		return this.masinf;
	}

	public void setMasinf(String masinf) {
		this.masinf = masinf;
	}

	@Column(name = "sector")
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

}
